#!/usr/bin/env python3
"""
The status dashboard: docs/status.html.

    python tools/build_dashboard.py        # write it
    python tools/build_dashboard.py --json # the same numbers, as data

Every number on the page is **measured from the repository**, not typed in.
That is the whole point: a hand-maintained status page is wrong within a week,
and a wrong status page is worse than none, because people act on it.

Where a number cannot be measured, the page says so rather than guessing.

Sources of every figure:

    TASKS.md                          phase checkboxes
    00-sources/metadata/claims.yaml   the TV -> V critical path
    00-sources/metadata/sources.yaml  editions, and what may be cited
    00-sources/source.db              corpus size, Arabic state (if built)
    00-foundations/citation-sheet.md  hadith card selection
    03-content/, 08-companions/,      what is actually written
    09-zines/, 04-art/artwork/
    README.md                         the blocking table, as its owner keeps it
    git                               last commit, and how old this build is

It is regenerated by tools/build_site.py, and by the GitHub Action on every
push, so it cannot drift from the repository it describes.
"""

import argparse
import datetime
import glob
import html
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs")


def read(path):
    p = os.path.join(ROOT, path)
    if not os.path.exists(p):
        return ""
    with open(p, encoding="utf-8") as f:
        return f.read()


def git(*args):
    try:
        r = subprocess.run(["git"] + list(args), cwd=ROOT, capture_output=True, timeout=30)
        return r.stdout.decode("utf-8", "replace").strip() if r.returncode == 0 else ""
    except Exception:
        return ""


# --------------------------------------------------------------------------
# collectors
# --------------------------------------------------------------------------

def phases():
    """Checkbox counts per phase, straight off TASKS.md."""
    out = []
    current = None
    for line in read("TASKS.md").split("\n"):
        m = re.match(r"^## (Phase \d+[^\n]*)", line)
        if m:
            current = {"name": m.group(1).strip(), "done": 0, "open": 0}
            out.append(current)
            continue
        if current is None:
            continue
        if re.match(r"^\s*- \[x\]", line, re.I):
            current["done"] += 1
        elif re.match(r"^\s*- \[ \]", line):
            current["open"] += 1
    for p in out:
        p["total"] = p["done"] + p["open"]
        p["pct"] = round(100 * p["done"] / p["total"]) if p["total"] else None
    return out


def claims():
    """The critical path. TV -> V, from the claim database."""
    try:
        from sourcelib import metadata
        rows = metadata.load_claims()
    except Exception as e:
        return {"available": False, "why": str(e)}
    by = {}
    for c in rows:
        by[c.get("status")] = by.get(c.get("status"), 0) + 1
    total = len(rows)
    return {
        "available": True,
        "total": total,
        "by_status": by,
        "verified": by.get("V", 0),
        "to_verify": by.get("TV", 0),
        "pct_verified": round(100 * by.get("V", 0) / total) if total else 0,
    }


def sources():
    try:
        from sourcelib import metadata
        works, editions, _ = metadata.load_sources()
    except Exception as e:
        return {"available": False, "why": str(e)}
    by = {}
    for e in editions:
        by[e.get("status")] = by.get(e.get("status"), 0) + 1
    held = [e for e in editions if e.get("status") != "missing"]
    return {
        "available": True,
        "works": len(works),
        "editions": len(editions),
        "by_status": by,
        "fixed": by.get("fixed", 0),
        "missing": by.get("missing", 0),
        "page_citable": sum(1 for e in held if e.get("pagination") == "printed"),
        "no_sha256": [e["source_id"] for e in held if not e.get("sha256")],
        "no_translator": [e["source_id"] for e in held if not e.get("translator")],
    }


def corpus():
    """Only if source.db has been built — it is not tracked."""
    db_path = os.path.join(ROOT, "00-sources", "source.db")
    if not os.path.exists(db_path):
        return {"available": False,
                "why": "source.db is not tracked — run tools/build_source_corpus.py"}
    try:
        import sqlite3
        con = sqlite3.connect("file:%s?mode=ro" % db_path, uri=True)
        con.row_factory = sqlite3.Row
        one = lambda q: con.execute(q).fetchone()[0]
        out = {
            "available": True,
            "pages": one("SELECT COUNT(*) FROM pages"),
            "passages": one("SELECT COUNT(*) FROM passages"),
            "quotation_ready": one("SELECT COUNT(*) FROM passages WHERE quotation_ready=1"),
            "arabic_passages": one("SELECT COUNT(*) FROM passages WHERE arabic_verified=0"),
            "arabic_unusable_editions": [
                r["source_id"] for r in con.execute(
                    "SELECT source_id FROM editions WHERE arabic_extraction='unusable'")],
        }
        con.close()
        return out
    except Exception as e:
        return {"available": False, "why": str(e)}


def storefront():
    """The shop's switches, read from the same file the shop is built from."""
    try:
        import build_shop
        store, products = build_shop.load_products()
    except Exception as e:
        return {"available": False, "why": str(e)}
    wl = store.get("waitlist") or {}
    legal = store.get("legal") or {}
    return {
        "available": True,
        "skus": len(products),
        "priced": sum(1 for p in products if p.get("price") is not None),
        "sellable": sum(1 for p in products if p.get("status") == "available"),
        "provider": (store.get("provider") or "none"),
        "published": bool(store.get("published")),
        "waitlist_open": bool(wl.get("endpoint") or wl.get("email")),
        "legal_set": bool(legal.get("entity") and legal.get("contact")),
    }


def _words(text):
    return len(re.findall(r"[A-Za-z'’\-]+", text))


def denies_hadith_card(body):
    """True when the file states the rule overturned on 2026-08-14."""
    return bool(re.search(r"No hadith card", body, re.I))


def reads_as_carrying_card(body):
    """True when the file gives the entry a hadith card.

    The negation matters more than the phrase. Every companion file used to
    read "No hadith card. No event print." — the old rule — so a bare search
    for "hadith card" reported all thirty-nine as carrying one, which was the
    exact opposite of what the files said.
    """
    return bool(re.search(r"hadith card", body, re.I)) and not denies_hadith_card(body)


def content():
    """What is actually written, measured by looking at the files."""
    envelopes = []
    for n in range(1, 15):
        num = "%02d" % n
        src = ("01-pilot/envelope-03/letter.md" if num == "03"
               else "03-content/envelope-%s.md" % num)
        body = read(src)
        envelopes.append({"num": num, "exists": bool(body), "words": _words(body)})

    companions = []
    for p in sorted(glob.glob(os.path.join(ROOT, "08-companions", "*.md"))):
        name = os.path.basename(p)
        if name.upper().startswith("README"):
            continue
        body = read("08-companions/" + name)
        companions.append({
            "slug": name[:-3], "words": _words(body),
            "has_hadith_card": reads_as_carrying_card(body),
            "states_overturned_rule": denies_hadith_card(body)})

    zines = []
    for p in sorted(glob.glob(os.path.join(ROOT, "09-zines", "*.md"))):
        name = os.path.basename(p)
        if (name.upper().startswith("README") or "template" in name.lower()
                or "outline" in name.lower()):
            continue
        body = read("09-zines/" + name)
        # A zine is one sheet folded to eight pages. Eight written pages is the
        # structural definition of finished, and it is what can be measured —
        # a word threshold would just be a guess about quality.
        pages_written = len(re.findall(r"^## PAGE \d", body, re.M))
        zines.append({"slug": name[:-3], "pages": pages_written, "words": _words(body),
                      "full": pages_written >= 8})

    art = [f for f in glob.glob(os.path.join(ROOT, "04-art", "artwork", "*"))
           if os.path.splitext(f)[1].lower() in (".png", ".jpg", ".jpeg", ".webp", ".svg",
                                                 ".tif", ".tiff")]
    return {
        "envelopes": envelopes,
        "envelopes_written": sum(1 for e in envelopes if e["exists"]),
        "companions": companions,
        "companions_written": len(companions),
        "companions_with_hadith_card": sum(1 for c in companions if c["has_hadith_card"]),
        "companions_stating_overturned_rule": sum(1 for c in companions
                                                  if c["states_overturned_rule"]),
        "zines": zines,
        "zines_full": sum(1 for z in zines if z["full"]),
        "zines_total": len(zines),
        "artwork_files": len(art),
    }


def hadith_cards():
    """Box cards and companion cards, read off the citation sheet's own tables."""
    try:
        from import_citation_sheet import parse_sheet, SHEET, clean
        rows, _, _, _ = parse_sheet(SHEET)
    except Exception as e:
        return {"available": False, "why": str(e)}
    # by envelope, not by row: envelope 03's card appears both in its own
    # section and in the all-fourteen table
    box = [c for c in rows if c.get("item") == "hadith card"]

    # The companions line has its own table, which the importer deliberately
    # does not turn into claims — in the sheet's own words, "the theme is the
    # search brief, not the citation. Nothing here is a claim about a text."
    # So it is read here directly, and counted as slots rather than claims.
    companion = {"total": 0, "selected": 0, "blocked": 0}
    in_table = False
    for line in read("00-foundations/citation-sheet.md").split("\n"):
        if line.startswith("#"):
            in_table = False
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        sig = tuple(c.lower() for c in cells)
        if sig[:2] == ("entry", "points to") and "saying" in sig and "status" in sig:
            in_table = True
            continue
        if not in_table or len(cells) < 6 or set("".join(cells)) <= set("-: "):
            continue
        companion["total"] += 1
        if "BLOCKED" in cells[5].upper():
            companion["blocked"] += 1
        elif clean(cells[4]) not in ("", "—", "-", "–"):
            companion["selected"] += 1

    return {
        "available": True,
        "box_total": 14,
        "box_selected": len({c.get("env") for c in box if c.get("status") == "V"}),
        "box_blocked": len({c.get("env") for c in box
                            if c.get("status") == "needs-review"}),
        "companion_total": companion["total"] or 39,
        "companion_selected": companion["selected"],
        "companion_blocked": companion["blocked"],
    }


def blockers():
    """The README's own blocking table. One source of truth, not a second one."""
    body = read("README.md")
    m = re.search(r"## What is blocking, right now\s*\n(.*?)(?=\n## |\Z)", body, re.S)
    if not m:
        return {"available": False, "why": "the blocking table in README.md has moved"}
    out = []
    for line in m.group(1).split("\n"):
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 3 or set("".join(cells)) <= set("-: "):
            continue
        if cells[0].lower() == "blocker":
            continue
        out.append({"blocker": cells[0], "blocks": cells[1], "owner": cells[2]})
    return {"available": True, "rows": out}


def build_info():
    return {
        "built_at": datetime.datetime.now(datetime.timezone.utc)
                             .replace(microsecond=0).isoformat(),
        "commit": git("rev-parse", "--short", "HEAD"),
        "commit_subject": git("log", "-1", "--format=%s"),
        "commit_date": git("log", "-1", "--format=%ad", "--date=short"),
        "branch": git("rev-parse", "--abbrev-ref", "HEAD"),
    }


def collect():
    return {
        "build": build_info(),
        "phases": phases(),
        "claims": claims(),
        "sources": sources(),
        "corpus": corpus(),
        "content": content(),
        "hadith_cards": hadith_cards(),
        "storefront": storefront(),
        "blockers": blockers(),
    }


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------

def bar(done, total, label=None):
    pct = round(100 * done / total) if total else 0
    lab = label or "%d / %d" % (done, total)
    return (f'<div class="meter" role="img" aria-label="{html.escape(lab)}">'
            f'<span style="width:{pct}%"></span></div>'
            f'<span class="meterlab">{html.escape(lab)}</span>')


def esc(x):
    return html.escape(str(x))


def render(d):
    S = []
    w = S.append

    b = d["build"]
    w('<section class="dashhero">')
    w("<h1>Status</h1>")
    w('<p class="lede">Every number here is measured from the repository at build '
      'time. Nothing on this page is typed in by hand, and nothing is an estimate. '
      'Where something cannot be measured, it says so.</p>')
    w('<p class="lede small">Built %s from <code>%s</code> on <code>%s</code> — '
      '%s</p>' % (esc(b["built_at"].replace("T", " ").replace("+00:00", " UTC")),
                  esc(b["commit"] or "unknown"), esc(b["branch"] or "?"),
                  esc(b["commit_subject"] or "")))
    w("</section>")

    # ---- the critical path -------------------------------------------
    c = d["claims"]
    hc = d["hadith_cards"]
    w('<section class="dash"><h2>The critical path — verification</h2>')
    if not c.get("available"):
        w('<p class="warn">Claim database unavailable: %s</p>' % esc(c.get("why")))
    else:
        w('<p class="sectionnote">A claim is <code>V</code> only when a person has '
          'opened the fixed edition at the named place. Nothing prints on '
          '<code>TV</code>.</p>')
        w('<div class="statrow">')
        w(stat("Claims verified", "%d / %d" % (c["verified"], c["total"]),
               bar(c["verified"], c["total"], "%d%% V" % c["pct_verified"])))
        w(stat("Still to verify", c["to_verify"], sub="status <code>TV</code>"))
        others = ", ".join("%s %d" % (k, v) for k, v in sorted(c["by_status"].items())
                           if k not in ("V", "TV"))
        w(stat("Other statuses", others or "—",
               sub="TRAD traditional · CONT contested · needs-review blocked"))
        w("</div>")
    if hc.get("available"):
        w('<div class="statrow">')
        w(stat("Box hadith cards", "%d / %d" % (hc["box_selected"], hc["box_total"]),
               bar(hc["box_selected"], hc["box_total"]),
               sub="%d blocked — no permitted source" % hc["box_blocked"]))
        w(stat("Companion hadith cards",
               "%d / %d" % (hc["companion_selected"], hc["companion_total"]),
               bar(hc["companion_selected"], hc["companion_total"]),
               sub="%d blocked — no permitted source, or no rule"
                   % hc["companion_blocked"]))
        w("</div>")
    w("</section>")

    # ---- what is written ---------------------------------------------
    ct = d["content"]
    w('<section class="dash"><h2>What is written</h2>')
    w('<p class="sectionnote">Measured by reading the files, not by a checklist.</p>')
    w('<div class="statrow">')
    w(stat("Envelope letters", "%d / 14" % ct["envelopes_written"],
           bar(ct["envelopes_written"], 14)))
    w(stat("Companion envelopes", "%d / 39" % ct["companions_written"],
           bar(ct["companions_written"], 39)))
    w(stat("Zines written in full", "%d / %d" % (ct["zines_full"], ct["zines_total"]),
           bar(ct["zines_full"], ct["zines_total"]),
           sub="all eight pages written"))
    w(stat("Illustrations", ct["artwork_files"],
           sub="image files in <code>04-art/artwork/</code>"
               + (" — prompts written, none run" if not ct["artwork_files"] else "")))
    w("</div>")
    if ct["companions_stating_overturned_rule"]:
        w('<p class="warn">The 2026-08-14 decision gave the companions line a hadith '
          'card and overturned the rule forbidding one. '
          '<strong>%d of %d companion files still state the overturned rule</strong> '
          '("No hadith card"), and %d carry one. Every published companion page '
          'therefore still shows the pre-decision item list.</p>'
          % (ct["companions_stating_overturned_rule"], ct["companions_written"],
             ct["companions_with_hadith_card"]))
    w("</section>")

    # ---- sources ------------------------------------------------------
    s = d["sources"]
    cp = d["corpus"]
    w('<section class="dash"><h2>The source library</h2>')
    if not s.get("available"):
        w('<p class="warn">Source metadata unavailable: %s</p>' % esc(s.get("why")))
    else:
        w('<div class="statrow">')
        w(stat("Editions fixed", "%d / %d" % (s["fixed"], s["editions"]),
               bar(s["fixed"], s["editions"]),
               sub=", ".join("%d %s" % (v, k) for k, v in sorted(s["by_status"].items()))))
        w(stat("Editions whose pages may be cited",
               "%d / %d" % (s["page_citable"], s["editions"] - s["missing"]),
               sub="every held edition is a web-generated or two-column PDF — "
                   "cite the work's own internal numbering"))
        w(stat("Editions not pinned by SHA-256", len(s["no_sha256"]),
               sub="an edition without a hash is not a fixed edition: "
                   + ", ".join("<code>%s</code>" % esc(x) for x in s["no_sha256"][:8])
               if s["no_sha256"] else "all pinned"))
        w(stat("Held with no translator credit", len(s["no_translator"]),
               sub=(", ".join("<code>%s</code>" % esc(x) for x in s["no_translator"])
                    + " — the project's own rule forbids citing them")
               if s["no_translator"] else "all credited"))
        w("</div>")
    if cp.get("available"):
        w('<div class="statrow">')
        w(stat("Pages indexed", "{:,}".format(cp["pages"])))
        w(stat("Passages", "{:,}".format(cp["passages"]),
               sub="%s fit to quote verbatim today" % "{:,}".format(cp["quotation_ready"])))
        w(stat("Arabic awaiting verification", "{:,}".format(cp["arabic_passages"]),
               sub="%d editions extract their Arabic as broken glyphs"
                   % len(cp["arabic_unusable_editions"])))
        w("</div>")
    else:
        w('<p class="sectionnote">Corpus statistics need <code>source.db</code>, which '
          'is not tracked (182 MB). %s</p>' % esc(cp.get("why", "")))
    w("</section>")

    # ---- storefront ---------------------------------------------------
    sf = d["storefront"]
    w('<section class="dash"><h2>Storefront</h2>')
    if not sf.get("available"):
        w('<p class="warn">Shop configuration unavailable: %s</p>' % esc(sf.get("why")))
    else:
        w('<p class="sectionnote">Three pages at <code>docs/shop/</code>, built from '
          '<code>06-commerce/products.yaml</code>. Read from that file, not typed here.</p>')
        w('<div class="statrow">')
        w(stat("SKUs defined", sf["skus"], sub="the five in the commerce plan"))
        w(stat("Priced", "%d / %d" % (sf["priced"], sf["skus"]),
               bar(sf["priced"], sf["skus"]),
               sub="no price exists in this repository yet"))
        w(stat("Payment provider", sf["provider"],
               sub="buy buttons stay inert until this is set"
                   if sf["provider"] == "none" else "wired"))
        w(stat("Search engines", "indexed" if sf["published"] else "noindex",
               sub="published: %s" % str(sf["published"]).lower()))
        w("</div>")
        if not sf["legal_set"]:
            w('<p class="warn">No seller entity, contact or privacy notice is set. '
              'An email address cannot be collected without them, so the waitlist '
              'renders a plain statement rather than a form.</p>')
    w("</section>")

    # ---- phases -------------------------------------------------------
    w('<section class="dash"><h2>Phases</h2>')
    w('<p class="sectionnote">Checkbox counts from <code>TASKS.md</code>. A ticked box '
      'is a claim by whoever ticked it, so this measures recorded progress, not '
      'finished work.</p>')
    w('<table class="dashtable"><thead><tr><th>Phase</th><th>Done</th>'
      '<th>Open</th><th></th></tr></thead><tbody>')
    for p in d["phases"]:
        w("<tr><td>%s</td><td>%d</td><td>%d</td><td>%s</td></tr>"
          % (esc(p["name"]), p["done"], p["open"],
             bar(p["done"], p["total"]) if p["total"] else "—"))
    w("</tbody></table></section>")

    # ---- blockers -----------------------------------------------------
    bl = d["blockers"]
    w('<section class="dash"><h2>Blocking, right now</h2>')
    if not bl.get("available"):
        w('<p class="warn">%s</p>' % esc(bl.get("why")))
    else:
        w('<p class="sectionnote">Read from the table in <code>README.md</code>, so '
          'there is one list and not two.</p>')
        w('<table class="dashtable"><thead><tr><th>Blocker</th><th>Blocks</th>'
          '<th>Owner</th></tr></thead><tbody>')
        for r in bl["rows"]:
            w("<tr><td>%s</td><td>%s</td><td>%s</td></tr>"
              % (md_inline(r["blocker"]), md_inline(r["blocks"]), md_inline(r["owner"])))
        w("</tbody></table>")
    w("</section>")
    return "\n".join(S)


def md_inline(text):
    """The little markdown the README tables use, and nothing else."""
    t = html.escape(text)
    t = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", t)
    t = re.sub(r"`([^`]+)`", r"<code>\1</code>", t)
    t = re.sub(r"\*(.+?)\*", r"<em>\1</em>", t)
    return t


def stat(label, value, meter=None, sub=None):
    parts = ['<div class="stat">', '<p class="statlab">%s</p>' % esc(label),
             '<p class="statval">%s</p>' % (value if isinstance(value, str)
                                            and "<" in str(value) else esc(value))]
    if meter:
        parts.append('<p class="statmeter">%s</p>' % meter)
    if sub:
        parts.append('<p class="statsub">%s</p>' % sub)
    parts.append("</div>")
    return "".join(parts)


def write_page():
    from build_site import page
    d = collect()
    os.makedirs(OUT, exist_ok=True)
    dest = os.path.join(OUT, "status.html")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(page("Status", "", render(d)))
    return dest


def main_from_site():
    """Called by build_site.build() so one command builds the whole site."""
    write_page()
    print("  status page built from live repository state")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    d = collect()
    if args.json:
        print(json.dumps(d, indent=2, ensure_ascii=False))
        return 0

    write_page()
    print("built docs/status.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
