#!/usr/bin/env python3
"""
Generate the citation sheet from the database, and compare it with the one in
00-foundations/.

    python tools/render_citation_sheet.py            # compare, report, change nothing
    python tools/render_citation_sheet.py --write    # write the generated view

This exists to answer one question: could `00-foundations/citation-sheet.md`
become a generated view instead of a hand-maintained file?

**It never writes to 00-foundations/citation-sheet.md.** The generated view goes
to 00-sources/reports/citation-sheet.generated.md, next to the audit. The
existing sheet is editorial work and is not overwritten by a tool.

The comparison is the point. It reports, per row, whether the database agrees
with the sheet on status, work and reference — so drift between them is visible
rather than discovered at print.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from sourcelib import config, db, metadata
from import_citation_sheet import parse_sheet, resolve_source, SHEET, clean


def load_db(con):
    claims = {r["claim_id"]: dict(r) for r in con.execute("SELECT * FROM claims")}
    cites = {}
    for r in con.execute("SELECT * FROM citations"):
        cites.setdefault(r["claim_id"], []).append(dict(r))
    eds = {r["source_id"]: dict(r) for r in con.execute("SELECT * FROM v_editions")}
    return claims, cites, eds


def compare(sheet_claims, sheet_cites, db_claims, db_cites, aliases):
    """Row by row. Anything the database cannot confirm is reported, not fixed."""
    findings = []
    stub_by_claim = {}
    for s in sheet_cites:
        stub_by_claim.setdefault(s["claim_id"], []).append(s)

    for c in sheet_claims:
        cid = c["claim_id"]
        d = db_claims.get(cid)
        if d is None:
            findings.append(("missing", cid, "on the sheet, not in the database — "
                                             "re-run tools/import_citation_sheet.py"))
            continue
        if d["status"] != c["status"]:
            findings.append(("status", cid,
                             "sheet says %s, database says %s" % (c["status"], d["status"])))

        want = stub_by_claim.get(cid, [])
        have = db_cites.get(cid, [])
        if want and not have:
            findings.append(("citation", cid, "sheet names a work, database has no citation"))
        for s in want:
            sid = resolve_source(s["work_text"], aliases)
            if sid is None:
                findings.append(("work", cid,
                                 "work %r on the sheet matches no edition in sources.yaml"
                                 % s["work_text"]))
            elif not any(h["source_id"] == sid for h in have):
                findings.append(("citation", cid,
                                 "sheet cites %s (%s), database does not"
                                 % (s["work_text"], sid)))

    for cid in db_claims:
        if not any(c["claim_id"] == cid for c in sheet_claims):
            findings.append(("orphan", cid, "in the database, not on the sheet"))
    return findings


def render(db_claims, db_cites, eds):
    """The generated view. Same columns as the sheet's own claim tables, plus the
    two things the sheet cannot carry by hand: a stable claim_id, and the exact
    passage the citation lands on."""
    groups = {}
    for c in db_claims.values():
        groups.setdefault(c["project_location"], []).append(c)

    L = ["# Citation sheet — generated view", "",
         "Generated by `tools/render_citation_sheet.py` from `00-sources/source.db`.",
         "",
         "**This is not the citation sheet.** `00-foundations/citation-sheet.md` is the "
         "editorial record and stays hand-maintained; this is what the database says about "
         "the same rows, for comparison. Statuses here are read from the database, never "
         "decided by it.", ""]

    for loc in sorted(groups):
        L.append("## %s" % loc.replace("00-foundations/citation-sheet.md § ", ""))
        L.append("")
        L.append("| claim_id | Env | Item | Claim | Source | Ref | Passage | Status |")
        L.append("|---|---|---|---|---|---|---|---|")
        for c in sorted(groups[loc], key=lambda x: (x["env"] or "", x["claim_id"])):
            cites = db_cites.get(c["claim_id"], [])
            src = ", ".join("`%s`" % ct["source_id"] for ct in cites) or "—"
            ref = ", ".join(str(ct["ref"] or "") for ct in cites) or "—"
            pas = ", ".join("`%s`" % ct["passage_id"] for ct in cites if ct["passage_id"]) or "—"
            claim = (c["claim_text"] or "").replace("|", "\\|")
            L.append("| `%s` | %s | %s | %s | %s | %s | %s | `%s` |" % (
                c["claim_id"], c["env"] or "—", c["item"] or "", claim, src,
                ref.replace("|", "\\|"), pas, c["status"]))
        L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sheet", default=SHEET)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--db", default=config.DB)
    args = ap.parse_args()

    sheet_claims, sheet_cites, _ = parse_sheet(args.sheet)
    con = db.connect(args.db, readonly=True)
    db_claims, db_cites, eds = load_db(con)
    _, editions, _ = metadata.load_sources()
    aliases = metadata.alias_map(editions)

    findings = compare(sheet_claims, sheet_cites, db_claims, db_cites, aliases)

    print("comparing %s with %s" % (os.path.relpath(args.sheet, config.ROOT),
                                    os.path.relpath(args.db, config.ROOT)))
    print("  sheet:    %d claim rows, %d citation rows" % (len(sheet_claims), len(sheet_cites)))
    print("  database: %d claims, %d citations"
          % (len(db_claims), sum(len(v) for v in db_cites.values())))
    if not findings:
        print("\n  ✓ every row on the sheet is represented in the database, with the same "
              "status, work and reference.")
    else:
        print("\n  %d difference(s):" % len(findings))
        for kind, cid, msg in findings:
            print("    [%s] %s — %s" % (kind, cid, msg))

    view = render(db_claims, db_cites, eds)
    if args.write:
        os.makedirs(config.REPORTS, exist_ok=True)
        dest = os.path.join(config.REPORTS, "citation-sheet.generated.md")
        with open(dest, "w", encoding="utf-8", newline="\n") as f:
            f.write(view)
        print("\nwrote %s" % os.path.relpath(dest, config.ROOT))

    print("""
Verdict on replacing the hand-maintained sheet
----------------------------------------------
The tables can be generated: every claim row round-trips through the database
with its status, work and reference intact, and the generated view adds two
things the sheet cannot hold by hand — a stable claim_id and the exact passage
a citation lands on.

What cannot be generated is the rest of the file, and it is most of its value:
the reasoning on the reverted envelope 03 rows, the account of the envelope 13
correction and why it was wrong, the two blocked hadith cards and what would
unblock them, the open questions. Those are editorial argument, not data.

Recommendation: keep 00-foundations/citation-sheet.md as the written record and
treat the database as the checkable index of it. Run this comparison to catch
drift. Do not replace the sheet.""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
